<?php

/**
 * Implements hook_menu
 */
function kompetenz_wort_visual_menu()
{
    $items['kompetenzwoerter'] = array(
        'title' => '',
        'description' => 'Kompetenzwoerter',
        'page callback' => 'show_network',
        'access callback' => TRUE,
    );

    $items['kompetenzwoerter/data'] = array(
        'title' => '',
        'description' => 'Kompetenzwoerter',
        'page callback' => 'getData',
        'access callback' => TRUE,
    );
    return $items;
}

function show_network() {
    $network_chart = array(
        'id' => 'visualization',
        'type' => 'kompetenz_words',
    );

    return d3_draw($network_chart);
}

function getData() {
    $query = 'SELECT body_value, entity_id AS nid FROM {field_data_body} WHERE bundle = :bundle';
    $result = db_query($query, array(':bundle' => 'projekt',));
    $projectWords = [];

    if ($result) {
        foreach ($result as $project) {
            $wordsFound = [];

            preg_match_all('/\w*kompetenz\w*/iu', $project->body_value, $wordsFound);

            // Array-Format key = gefundenes Kompetenzwort, value = wie oft das Wort im Text vorkommt wurde
            $wordsFrequency = array_count_values($wordsFound[0]);

            $projectWords[$project->nid] = $wordsFrequency;
        }
    }



    $projects = array_filter($projectWords);
    $keys = array_keys($projects);


    foreach($projects as $key => $value) {
        //dsm($key . "dhdhd" . $value);

    }
    $arr = $projects;
    foreach ($arr as $keyOut => $out) {
        foreach($out as $keyIn => $value) {
            dsm("key = (" . $keyOut . ", " . $keyIn. "), value = " . $value . "\n");
        }
    }


    return['#markup' => 'Hallo'];
}