<?php

/**
 * Implements hook_menu
 */
function kompetenz_wort_visual_menu()
{
    $items['kompetenzwoerter'] = array(
        'title' => '',
        'description' => 'Kompetenzwoerter',
        'page callback' => 'show_network',
        'access callback' => TRUE,
    );

    $items['kompetenzwoerter/data'] = array(
        'title' => '',
        'description' => 'Kompetenzwoerter',
        'page callback' => 'getData',
        'access callback' => TRUE,
    );
    return $items;
}

function show_network() {
    $network_chart = array(
        'id' => 'visualization',
        'type' => 'kompetenz_words',
    );
    getData();
    return d3_draw($network_chart);
}

function getData() {
    $query = 'SELECT body_value, entity_id AS nid FROM {field_data_body} WHERE bundle = :bundle';
    $result = db_query($query, array(':bundle' => 'projekt',));
    $graphdata = [];

    if ($result) {
        $index = 0;
        foreach ($result as $project) {
            $wordsFound = [];

            preg_match_all('/\w*kompetenz\w*/iu', $project->body_value, $wordsFound);

            // Array-Format key = gefundenes Kompetenzwort, value = wie oft das Wort im Text vorkommt wurde
            if ($wordsFound[0]) {
                $projectTitle = node_load($project->nid)->title;
                $wordsFrequency = array_count_values($wordsFound[0]);

                $graphdata[nodes][] = [name => $projectTitle];
                $projectIndex = $index++;

                foreach ($wordsFrequency as $word => $wordcount) {
                  // if it's a new 'kompetenz' word, add it as a node
                  $wordIndex = array_search($word, array_column($graphdata[nodes], name));
                  if ($wordIndex === false) {
                    $graphdata[nodes][] = [name => $word];
                    $wordIndex = $index++;
                  }

                  $graphdata[edges][] = [source => $projectIndex, target => $wordIndex];
                  $graphdata[praedikate][] = $wordcount;
                }
            }
        }
    }

    drupal_add_js(array('kompetenz_word_visual' => array('graphdata' => $graphdata)), array('type' => 'setting'));

    /*$projects = array_filter($projectWords);
    $keys = array_keys($projects);


    foreach($projects as $key => $value) {
        //dsm($key . "dhdhd" . $value);

    }
    $arr = $projects;
    foreach ($arr as $keyOut => $out) {
        foreach($out as $keyIn => $value) {
            dsm("key = (" . $keyOut . ", " . $keyIn. "), value = " . $value . "\n");
        }
    }


    return['#markup' => 'Hallo'];*/
}
